### ISSUE TITLE
Reduce output size

### ISSUE THREAD

**Issue by mcremone** [LPC-DM/PandaAnalysis#38]
The output of PandaAnalysis is too big. It shouldn't be a problem of preselection, I suspect we are simply saving too much information. This prevents us from getting a manageable output to do the next steps. Should be checked and possibly solved by this Tuesday.

@sudhaahuja @gurpinar @smdogra @DianaLeonS @SiewYan @sundleeb @yguler

**Comment by mcremone** [comment]
Any update>

**Comment by SiewYan** [comment]
For boosted, the total output (merged samples data and backgrounds) is 30 GB. 
Brief inspection on the boosted template wrt to darkHiggs reveals:

skim_boosted_tmpl.py ->
kRecoil,  (max_pfDown>250 || max_pf>250 || max_pfUp>250 || max_puppi>250)

skim_darkhiggs_tmpl.py ->
kMonohiggs, (gt->nFatjet>=1 && gt->fj1Pt>150)  (max_pf>250 || max_puppi>250)

The implemented skim_boosted_tmpl.py missing selection on Fatjets.

**Comment by mcremone** [comment]
I realized that the preselection is completely dominated by the recoil cut. I then took out the fat jet pT cut and changed the skim_boosted_tmpl.py accordingly. It all good.

**Comment by sundleeb** [comment]
Various unused variables have been removed from panda analysis code which hopefully will lead in reduction of the output size considerably.
